export const patients: Patient[] = [
  {
    id: "P001",
    name: "John Doe",
    age: 35,
    dietType: "non-veg",
    weight: 78,
    height: 180,
    bloodGroup: "O+",
    medicalHistory: ["Hypertension", "Asthma"],
    prescriptions: ["Losartan 50mg", "Salbutamol Inhaler"],
    email: "john.doe@example.com",
    phone: "123-456-7890",
    address: "123 Elm Street, Springfield, IL, USA",
  },
  {
    id: "P002",
    name: "Emma Watson",
    age: 29,
    dietType: "veg",
    weight: 60,
    height: 165,
    bloodGroup: "A+",
    medicalHistory: ["Iron Deficiency"],
    prescriptions: ["Ferrous Sulfate 325mg"],
    email: "emma.watson@example.com",
    phone: "987-654-3210",
    address: "456 Maple Avenue, London, UK",
  },
  {
    id: "P003",
    name: "Rajesh Kumar",
    age: 42,
    dietType: "veg",
    weight: 85,
    height: 175,
    bloodGroup: "B+",
    medicalHistory: ["Type 2 Diabetes"],
    prescriptions: ["Metformin 500mg"],
    email: "rajesh.kumar@example.com",
    phone: "789-123-4567",
    address: "78 Gandhi Road, Mumbai, India",
  },
  {
    id: "P004",
    name: "Sophia Martinez",
    age: 50,
    dietType: "non-veg",
    weight: 70,
    height: 160,
    bloodGroup: "AB-",
    medicalHistory: ["Chronic Kidney Disease", "Hypercholesterolemia"],
    prescriptions: ["Atorvastatin 10mg", "Erythropoietin Injection"],
    email: "sophia.martinez@example.com",
    phone: "654-321-9870",
    address: "12 Oak Street, Madrid, Spain",
  },
  {
    id: "P005",
    name: "Liam Johnson",
    age: 24,
    dietType: "non-veg",
    weight: 68,
    height: 175,
    bloodGroup: "O-",
    medicalHistory: ["No known conditions"],
    prescriptions: [],
    email: "liam.johnson@example.com",
    phone: "321-654-0987",
    address: "22 Pine Lane, Sydney, Australia",
  },
];
